# Generated by Django 3.2.6 on 2021-11-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_img_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
    ]
