# Generated by Django 3.2.6 on 2021-11-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
